- block:
  - name: Get Ubuntu version
    raw: lsb_release -rs
    register: ubuntu_version
    changed_when: false
  - name: Set ansible_python_interpreter for Ubuntu >= 18.04
    set_fact:
      ansible_python_interpreter: python3
    when: ubuntu_version.stdout | trim is version('18.04', '>=')
  when: ansible_python_interpreter is not defined
  tags: always
